import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import frontcard from '../images/bg-card-front.png'
import backcard from '../images/bg-card-back.png'
import cardlogo from '../images/card-logo.svg'
import iconcomplete from '../images/icon-complete.svg'
import SignUpForm from '../components/SignUpForm'
import { useState } from 'react'

const ThankYouComponent = () => {
  return (
    <div className={styles.thankyou}>
      <Image src={iconcomplete} className={styles.complete} alt="complete-image"/>
      <h1 className={styles.thankyouheader}>THANK YOU!</h1>
      <div className={styles.desc}>We&#39;ve added your card details</div>
      <button className={styles.continue}>Continue</button>
    </div>
  )
}


export default function Home() {
  const [ form, setForm] =  useState({
    name: "JANE APPLESEED",
    cardNumber: "0000 0000 0000 0000",
    expMonth: "00",
    expYear: "00",
    cvc: "000",
    submitted: false
  })

  return (
    <>
      <Head>
        <title>Interactive card details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.left}>
          <div className={styles.frontcard}>
            <label className={styles.cardnumberlabel}>{form.cardNumber}</label>
            <label className={styles.namelabel}>{form.name}</label>
            <label className={styles.explabel}>{form.expMonth + "/" + form.expYear }</label>
          </div>
          <div className={styles.backcard}>
            <label className={styles.cvclabel}>{form.cvc}</label>
          </div>

        </div>

        <div className={styles.right}>
          {form.submitted ? <ThankYouComponent></ThankYouComponent> : <SignUpForm form={form} setForm={setForm}></SignUpForm>}

        </div>

      </main>
      <footer className="attribution">
    Challenge by <a href="https://www.frontendmentor.io?ref=challenge">Frontend Mentor</a>.
    Coded by <a href="#">Salman Hossain</a>.
  </footer>
    </>
  )
}
